### ISSUE TITLE
missing VM configuration events

### ISSUE THREAD

**Issue by martinpitt** [larskarlitski/libvirt-dbus#2]
For replacing Cockpit's current functinoality, I would need the following events/signals for a particular machine: metadata-change, device-added, device-removed, disk-change, tray-change

**Comment by larskarlitski** [comment]
Added `DeviceAdded` and `DeviceRemoved` in 2267828 and `DiskChange` and `TrayChange` in dcf2e73. I've left the inconsistent naming in place :(

Which libvirt version are we targetting? `MetadataChange` is not available on my fedora 25. @Antique, when was that added?

**Comment by Antique** [comment]
libvirt-v3.0.0

**Comment by Antique** [comment]
The libvirt-dbus code will probably need to check whether an event in question is available before registering in order to support older versions of libvirt API by the libvirt-dbus binding.

**Comment by martinpitt** [comment]
I'm not actually sure what metadata-change means, I haven't seen it in practice. My intent is to re-read the VM config/state on all events which might change it, so I thought I'd err on the safe side by including it. Fine for me to leave it out for now, if it's not important.

**Comment by larskarlitski** [comment]
`metadata-change` is fired when the `title`, `description`, or  anything in `<metadata>` changed. We do need that to update the UI, but I'm not sure if it's worth dropping support for 2.x only for that.

**Comment by Antique** [comment]
We should support all available events so this construction would allow to write a code that can be used with any version of libvirt, it will register all available events:
`for (i = 0; i < VIR_DOMAIN_EVENT_ID_LAST; i++) { ... }`.

**Comment by larskarlitski** [comment]
@Antique, that won't work without code generation, because libvirt doesn't give us string represenations for those enum values.

**Comment by Antique** [comment]
Right, it would require to build the libvirt-dbus against new enough libvirt in order to run it with older libvirt. I should start with the code generation :)

**Comment by martinpitt** [comment]
I don't see "metadata" in `virsh dump`, but if it's just things like title or description, I don't need that for porting cockpit at least.

**Comment by martinpitt** [comment]
Closing as the add/remove bits are in git now, thanks!
