### ISSUE TITLE
GetStats() should return dict, not singleton list of dicts

### ISSUE THREAD

**Issue by martinpitt** [larskarlitski/libvirt-dbus#6]
The `GetStats()` method wraps [virDomainListGetStats](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainListGetStats). However, on D-Bus it always applies to just that one domain, never to a list. Therefore it is confusing to return a singleton list, it should just directly return a dict (i. e. a{sv}).

**Comment by larskarlitski** [comment]
Sorry, I don't understand: it converts the first element of the list returned by `virDomainListGetStats` into an `a{sv}` and returns that as the only value (see [line 356 in manager.c](https://github.com/larskarlitski/libvirt-dbus/blob/master/src/manager.c#L356)).

Calling `busctl` confirms this:
```
$ busctl --user --verbose call org.libvirt /org/libvirt/domain/_372b25626_2d56cc_2d4f19_2db17f_2d556f89124f6e org.libvirt.Domain GetStats uu 0 0
MESSAGE "a{sv}" {
        ARRAY "{sv}" {
                DICT_ENTRY "sv" {
                        STRING "state.state";
                        VARIANT "i" {
                                INT32 1;
                        };
                };
                [...]
```

**Comment by martinpitt** [comment]
Sorry about that, this is an apparent pilot error on the cockpit.dbus API then: invocation.done() always returns a list with the return values.
